spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense
    username: expense_admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect